apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torch-checkpoint-pvc
  namespace: redhat-ods-operator
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage-provisioner
  resources:
    requests:
      storage: 5Gi