apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: torch-distributed-cpu-ppc64le-checkpoint
  labels:
    trainer.kubeflow.org/framework: torch
spec:
  mlPolicy:
    numNodes: 2
    torch: {}

  template:
    spec:
      replicatedJobs:
        - groupName: default
          name: node
          replicas: 1

          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer

            spec:
              template:
                spec:
                  containers:
                    - name: node
                      image: quay.io/puneesha/th-torch-cpu-py312:ppc64le ### update this to the correct image name
                      imagePullPolicy: IfNotPresent

                      volumeMounts:
                        - name: checkpoint-storage
                          mountPath: /mnt/checkpoints

                  volumes:
                    - name: checkpoint-storage
                      persistentVolumeClaim:
                        claimName: torch-checkpoint-pvc